# Generated by Django 5.1.2 on 2024-10-31 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
        ('ServiceManagement', '0002_itemcategory_itemtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ServiceManagement.service'),
            preserve_default=False,
        ),
    ]
