# Generated by Django 5.1.2 on 2024-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_orderlineitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ristorune',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
