# Generated by Django 5.1.2 on 2024-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0008_batch_orderlineitem_description_orderlineitem_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
