# Generated by Django 5.1.2 on 2024-11-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0009_alter_order_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Laundry', 'En production'), ('Returned', 'Retourner'), ('Completed', 'Terminer')], default='In Laundry', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Laundry', 'In Laundry'), ('Returned', 'Returned'), ('Completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('production', 'In Production'), ('Terminer', 'Done'), ('Livrer', 'Delivered')], default='pending', max_length=50),
        ),
    ]
