# Generated by Django 5.1.2 on 2024-11-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0010_alter_batch_status_alter_order_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('in_production', 'In Production'), ('completed', 'Completed')], default='in_production', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='ristourne',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial_production', 'Partial Production'), ('production', 'Production'), ('complete', 'Complete'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('production', 'In Production'), ('complete', 'Complete'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
