# Generated by Django 5.1.2 on 2024-11-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0011_alter_batch_status_alter_order_ristourne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'Pending'), ('partial_production', 'Partial Production'), ('production', 'Production'), ('complete', 'Complete'), ('delivered', 'Delivered')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'Pending'), ('production', 'In Production'), ('complete', 'Complete'), ('delivered', 'Delivered')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile Money')], max_length=20),
        ),
    ]
