# Generated by Django 5.1.2 on 2024-11-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0012_alter_order_status_alter_orderlineitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('partial', 'Paiement partiel'), ('complete', 'Complet')], default='pending', max_length=50),
        ),
    ]
