# Generated by Django 5.1.2 on 2024-11-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0014_order_annomaly_order_brand_order_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='annomaly',
            new_name='anomaly',
        ),
    ]
