# Generated by Django 5.1.2 on 2024-11-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0015_rename_annomaly_order_anomaly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='anomaly',
            new_name='anormaly',
        ),
    ]
