# Generated by Django 5.1.2 on 2024-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0016_rename_anomaly_order_anormaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='anormaly',
        ),
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='anormaly',
            field=models.CharField(choices=[('dechirure', 'Dechirure'), ('tache', 'Tache'), ('moisty', 'Moisissure')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
