# Generated by Django 5.1.2 on 2024-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0018_alter_order_balance_alter_orderlineitem_anormaly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
