# Generated by Django 5.1.2 on 2024-11-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('OrderManagement', '0020_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.salesession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.salesession'),
        ),
    ]
