# Generated by Django 5.1.2 on 2024-11-08 11:49

import OrderManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0021_order_session_payment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=OrderManagement.models.default_two_days_later, null=True),
        ),
    ]
