# Generated by Django 5.1.2 on 2024-11-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0022_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='anormaly',
            field=models.CharField(choices=[('Dechirure', 'Dechirure'), ('Tache', 'Tache'), ('Moisissure', 'Moisissure'), ('Teinte', 'Teinte'), ('Delaver', 'Delaver'), ('Trou', 'Trou'), ('Rouille', ' Rouille'), ('Boue', 'Boue'), ('Encre', 'Encre'), ('Aureole', 'Aureole'), ('Brullure', 'Brullure'), ('Effiloche', 'Effiloche'), ('Deteint', 'Deteint'), ('Decousu', 'Decousu'), ('Bouton Manquant', 'Bouton Manquant')], max_length=255, null=True),
        ),
    ]
