# Generated by Django 5.1.2 on 2024-11-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0023_alter_orderlineitem_anormaly'),
        ('UserManagement', '0003_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.agency'),
        ),
        migrations.AddField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.agency'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
