# Generated by Django 5.1.2 on 2024-11-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManagement', '0001_initial'),
        ('UserManagement', '0002_userprofile_quartier_userprofile_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='UserManagement.userprofile'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to='UserManagement.userprofile'),
        ),
        migrations.AlterField(
            model_name='expensepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], max_length=50),
        ),
    ]
