# Generated by Django 5.1.2 on 2024-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManagement', '0003_expense_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], default='cash', max_length=50),
            preserve_default=False,
        ),
    ]
