# Generated by Django 5.1.2 on 2024-10-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quartier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mme', 'Mme'), ('Mlle', 'Mlle'), ('Entreprise', 'Entreprise')], default='Mr', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
